name: Test

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 19.1.0
      - name: Install and start sidecar
        run: |
          cd sidecar 
          npm install
          npm run start &
      - name: Build and test
        run: sbt -v +test
